### ISSUE TITLE
Reflected Text .Net

### ISSUE THREAD

**Issue by BC89** [selectpdf/selectpdf-api-dotnet-client#2]
![image](https://user-images.githubusercontent.com/3298355/102381183-e8e68d80-3f96-11eb-8dd8-a3a6df88cb48.png)

I've been playing around with this product to determine whether to make a purchase. Every so often I get the funky reflection text output using the latest .Net  SDK. I pulling in HTML strings on the fly and building up my PDF.

**Comment by selectpdf** [comment]
Please provide a way for us to reproduce this problem (source url, generated pdf, code).

**Comment by selectpdf** [comment]
No response from issue reporter.
