### ISSUE TITLE
The Uri string is too long

### ISSUE THREAD

**Issue by grant007** [selectpdf/selectpdf-api-dotnet-client#3]
I make a call to convertHtmlStringToStream() passing a html string that is > 65K in length and the following error is thrown...
{"Invalid URI: The Uri string is too long."}	System.UriFormatException

Is there a limit to the length of the html string? Please advise.

**Comment by selectpdf** [comment]
We are working to fix this.

**Comment by selectpdf** [comment]
The issue is now fixed (please see version 1.1.1).
