### ISSUE TITLE
PDF rasterize clearing form

### ISSUE THREAD

**Issue by BC89** [selectpdf/selectpdf-api-dotnet-client#4]
[880.pdf](https://github.com/selectpdf/selectpdf-api-dotnet-client/files/7487930/880.pdf)

Using the .Net SDK rasterizing the attached clears the form altogether.  I've tried to play around with RGB, Grayscale and PNG, JPG

.Net Core 3.1

```
<PackageReference Include="Select.Pdf.NetCore" Version="21.1.0" />

 private byte[] RaterizeDoc(byte[] srcDoc)
        {
            PdfDocument finalDoc = new PdfDocument();

            PdfRasterizer rasterizer = new PdfRasterizer();

            rasterizer.Load(srcDoc);

            rasterizer.Resolution = 200;
            rasterizer.ColorSpace = PdfRasterizerColorSpace.RGB;
            rasterizer.ImagesFormat = System.Drawing.Imaging.ImageFormat.Png;

            System.Drawing.Image[] images = rasterizer.ConvertToImages();

            foreach (var img in images)
            {
                finalDoc.AddPage().Add(new PdfImageElement(0, 0, img));
            }

            return finalDoc.Save();
        }
```

**Comment by selectpdf** [comment]
Indeed, when you have a form in your pdf it happens what you describe. To avoid the problem, before rasterization, you need to flatten the form. Here is some code for it:

```
            PdfFormManager form = new PdfFormManager();
            form.Load(@"file-in.pdf");
            form.Flatten = true;
            form.Save(@"file-out.pdf");

```

**Comment by BC89** [comment]
So what is problematic is that in the same set of PDFs, some bomb silently when calling the flatten function. I went to the rasterize strategy as a workaround for the flatten error. So with both flatten and rasterize bugs, what is the alternative?

**Comment by selectpdf** [comment]
Please send us the pdfs with the problem and we will take a look.

**Comment by BC89** [comment]
[f6e05743-75f9-4b54-9944-5a0dd9064aec.pdf](https://github.com/selectpdf/selectpdf-api-dotnet-client/files/7497633/f6e05743-75f9-4b54-9944-5a0dd9064aec.pdf)

I didn't design these but the form does validate despite it's ugliness. It's during the Save that SelectPDF errors out and doesn't return. 

```
var pdfFlat = new PdfFormManager();

                        pdfFlat.Load(p.ArtifacteBytes); 

                        if (pdfFlat.Fields != null)
                        {
                            pdfFlat.Flatten = true;
                        }

                        var pf = pdfFlat.Save();
```

**Comment by BC89** [comment]
Any feedback on this item? Not sure why it was closed so quickly. Seems to me there's definitely an issue here either with rasterize and/or the flattening. 

Thx,
-BC

**Comment by selectpdf** [comment]
It was closed because this is not the appropriate location for this bug. It refers to the .NET library and here on Github this is another product: online REST API client for .NET. We are still working on this, but I would appreciate an email to our support address.

**Comment by BC89** [comment]
Sounds good. Thanks!

From: SelectPdf ***@***.***>
Sent: Wednesday, November 10, 2021 9:37 AM
To: selectpdf/selectpdf-api-dotnet-client ***@***.***>
Cc: Brendan Carroll ***@***.***>; Author ***@***.***>
Subject: [External Email] Re: [selectpdf/selectpdf-api-dotnet-client] PDF rasterize clearing form (Issue #4)

***From ***@***.******@***.***> 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
It was closed because this is not the appropriate location for this bug. It refers to the .NET library and here on Github this is another product: online REST API client for .NET. We are still working on this, but I would appreciate an email to our support address.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect-us.mimecast.com/s/sHsGC68z9DuPzkMGIpjXO1?domain=github.com>, or unsubscribe<https://protect-us.mimecast.com/s/_tjAC73WXEszlMyWHWHhs5?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-us.mimecast.com/s/X8HZC82BEGTX13QwH2a3Cr?domain=apps.apple.com> or Android<https://protect-us.mimecast.com/s/8R4zC9rLgJFzQnxYHOGXPk?domain=play.google.com>.

**Comment by BC89** [comment]
Hello,

Any update on this item? My team is scrambling with workarounds at present.

-BC

From: Brendan Carroll
Sent: Wednesday, November 10, 2021 9:42 AM
To: selectpdf/selectpdf-api-dotnet-client ***@***.***>; selectpdf/selectpdf-api-dotnet-client ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External Email] Re: [selectpdf/selectpdf-api-dotnet-client] PDF rasterize clearing form (Issue #4)

Sounds good. Thanks!

From: SelectPdf ***@***.******@***.***>>
Sent: Wednesday, November 10, 2021 9:37 AM
To: selectpdf/selectpdf-api-dotnet-client ***@***.******@***.***>>
Cc: Brendan Carroll ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External Email] Re: [selectpdf/selectpdf-api-dotnet-client] PDF rasterize clearing form (Issue #4)

***From ***@***.******@***.***> 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
It was closed because this is not the appropriate location for this bug. It refers to the .NET library and here on Github this is another product: online REST API client for .NET. We are still working on this, but I would appreciate an email to our support address.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect-us.mimecast.com/s/sHsGC68z9DuPzkMGIpjXO1?domain=github.com>, or unsubscribe<https://protect-us.mimecast.com/s/_tjAC73WXEszlMyWHWHhs5?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-us.mimecast.com/s/X8HZC82BEGTX13QwH2a3Cr?domain=apps.apple.com> or Android<https://protect-us.mimecast.com/s/8R4zC9rLgJFzQnxYHOGXPk?domain=play.google.com>.
